output_dir: "results/" # Base dir for plots/stats

data:
  test_file: "kaggle/input/mde-dataset-path/endoslam_test_files_with_gt_Stomach.txt"
  image_size: [224, 224]

model:
  backbone_size: "base"
  r: 4
  decode_type: "linear4"
  dropout_p: 0.1

evaluation:
  run_evidential: true
  run_mc_dropout: true
  evidential_checkpoint: "checkpoints/evidential/model_epoch_7.pth"
  mc_dropout_checkpoint: "checkpoints/mc_dropout_run_1/model_epoch_6.pth"
  
  mc_iterations: 50  # Num passes for final eval
  epsilon: 1.0e-6
  scatter_plot_name: "rmse_vs_confidence.png"
  
plotting:
  output_dir: "results/qualitative_plots"
  num_samples_to_plot: 50